deploy:
  stage: deploy
  script:
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H "$SSH_HOST" >> ~/.ssh/known_hosts
    - chmod 600 ~/.ssh/known_hosts
    - |
      ssh $SSH_USER@$SSH_HOST <<'EOF'
      echo "Debug: Checking variables"
      echo "CI_REGISTRY_USER: $CI_REGISTRY_USER"
      echo "CI_REGISTRY: $CI_REGISTRY"
      echo "Attempting docker login"
      printf "%s" "$CI_REGISTRY_PASSWORD" | docker login "$CI_REGISTRY" -u "$CI_REGISTRY_USER" --password-stdin
      if [ $? -ne 0 ]; then
        echo "Docker login failed"
        exit 1
      fi
      echo "Docker login succeeded"
      EOF
    - scp docker-compose.production.yml ${SSH_USER}@${SSH_HOST}:/home/${SSH_USER}/docker-compose.yml
    - ssh $SSH_USER@$SSH_HOST "docker compose -f /home/${SSH_USER}/docker-compose.yml pull && docker compose -f /home/${SSH_USER}/docker-compose.yml up -d --remove-orphans"
  tags:
    - docker
  only:
    - main
