stages:
  - build

image: docker:latest

services:
  - docker:dind

before_script:
  - docker info


build:
  stage: build
  script:
    - docker buildx build --platform linux/amd64 -t ${CI_REGISTRY}/library_management_system/sdt_project_group_05:latest -f user_management_service/compose/local/django/Dockerfile .
  tags:
    - docker