version: "3"
services:
  front_end:
    build: ./frontend
    container_name: front_end_c_dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true
