version: "3.8"
services:
  front-end:
    image: front-end-i
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: front_end_c_prod
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production
