# Generated by Django 5.0.9 on 2025-01-09 19:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_id', models.CharField(max_length=255, unique=True)),
                ('member_id', models.IntegerField()),
                ('body', models.TextField()),
                ('sent_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('reservation_id', models.IntegerField()),
                ('is_sent', models.BooleanField(default=False)),
            ],
        ),
    ]
