#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


cd reservation_service
python manage.py makemigrations
python manage.py migrate
python manage.py collectstatic --noinput

# python manage.py schedule_tasks

celery -A reservation_service worker --loglevel=info &
# celery -A reservation_service beat --loglevel=info &
exec python manage.py runserver_plus 0.0.0.0:8000 --reloader-type stat
