#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


cd reservation_service
python manage.py migrate
python manage.py collectstatic --noinput
exec python manage.py runserver_plus 0.0.0.0:8080
