# Generated by Django 5.0.9 on 2024-12-24 15:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.IntegerField()),
                ('book_group_id', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('notified', 'Notified'), ('accepted', 'Accepted'), ('canceled', 'Canceled')], default='pending', max_length=10)),
                ('reservation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('notification_datetime', models.DateTimeField(blank=True, null=True)),
                ('response_deadline', models.DateTimeField(blank=True, null=True)),
                ('user_response', models.CharField(blank=True, choices=[('accept', 'Accept'), ('skip', 'Skip'), ('cancel', 'Cancel')], max_length=10, null=True)),
            ],
        ),
    ]
