# Generated by Django 5.0.9 on 2024-12-30 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('notified', 'Notified'), ('accepted', 'Accepted'), ('canceled', 'Canceled'), ('expired', 'Expired')], default='pending', max_length=10),
        ),
    ]
