#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

cd user_management
# python manage.py collectstatic --noinput
exec gunicorn user_management.wsgi:application --bind 0.0.0.0:8000 --chdir=/app
