# Generated by Django 5.0.9 on 2025-01-08 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='book_copy_id',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='member_id',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='returned_date',
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_date',
            field=models.DateField(),
        ),
    ]
