# Generated by Django 5.0.9 on 2025-01-08 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0003_loan_book_copy_id_loan_member_id_loan_returned_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='returned_date',
        ),
    ]
