# Generated by Django 5.0.9 on 2025-01-08 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0005_loan_returned_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='returned_date',
        ),
    ]
