# Generated by Django 5.0.9 on 2025-01-08 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0006_remove_loan_returned_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='returned_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
