# Generated by Django 5.0.9 on 2025-01-08 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0007_loan_returned_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='returned_date',
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
