# Generated by Django 5.0.9 on 2025-01-08 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0011_loan_returned_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
