#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

cd notification_service
python manage.py collectstatic --noinput
exec gunicorn notification.wsgi:application --bind 0.0.0.0:8000 --chdir=/app
celery -A notification worker --loglevel=info &
