# Generated by Django 5.0.9 on 2024-11-20 23:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.contrib.auth.hashers import make_password


def create_initial_data(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Institution = apps.get_model('member_auth', 'Institution')
    User = apps.get_model('auth', 'User')
    UserProfile = apps.get_model('member_auth', 'UserProfile')

    group_names = ['member', 'staff_member', 'admin']
    groups = {name: Group.objects.get_or_create(name=name)[0] for name in group_names}

    institutions = ['IPB - ESTIG', 'Technical University of Moldova', 'UTFPR']
    institution_objects = {name: Institution.objects.get_or_create(name=name)[0] for name in institutions}

    admin_username = "admin"
    admin_email = "admin@admin.com"
    admin_password = "123"

    hashed_password = make_password(admin_password)

    admin_user, created = User.objects.get_or_create(
        username=admin_username,
        defaults={
            'email': admin_email,
            'is_staff': True,
            'is_superuser': True,
            'password': hashed_password
        }
    )

    admin_user.groups.add(groups['admin'])

    institution = institution_objects['IPB - ESTIG']
    UserProfile.objects.get_or_create(user=admin_user, defaults={'institution': institution})


class Migration(migrations.Migration):

    dependencies = [
        ('member_auth', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='member_auth.institution')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(create_initial_data),
    ]
