# Generated by Django 5.0.9 on 2024-11-17 23:27

from django.db import migrations


def add_groups_and_institutions(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    group_names = ['member', 'staff_member', 'admin']
    for name in group_names:
        Group.objects.get_or_create(name=name)

    Institution = apps.get_model('member_auth', 'Institution')
    institutions = ['IPB - ESTIG', 'Technical University of Moldova', 'UTFPR']
    for name in institutions:
        Institution.objects.get_or_create(name=name)


class Migration(migrations.Migration):
    dependencies = [
        ('member_auth', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_groups_and_institutions),
    ]
