# Generated by Django 5.0.9 on 2025-01-05 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcopy',
            name='book_code',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
