# Generated by Django 5.0.9 on 2025-01-05 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_bookcopy_book_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcopy',
            name='book_code',
            field=models.CharField(max_length=255),
        ),
    ]
