# Generated by Django 5.0.9 on 2025-01-05 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_bookcopy_book_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookcopy',
            name='book_code',
        ),
    ]
