# Generated by Django 5.0.9 on 2025-01-09 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_remove_bookcopy_book_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='institution',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Institution',
        ),
    ]
