# Generated by Django 5.0.9 on 2025-01-10 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_book_institution_delete_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcopy',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bookcopy',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('unavailable', 'Unavailable')], default='available', max_length=12),
        ),
    ]
