FROM node:18-alpine AS build
WORKDIR /app
COPY frontend ./
RUN npm ci --only=production
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]