FROM node:18-alpine AS build
WORKDIR /app
COPY frontend/package.json frontend/package-lock.json ./
RUN npm install

# Adicione uma etapa de depuração para listar as dependências instaladas
RUN ls -la node_modules
RUN ls -la node_modules/react-scripts

COPY . .
RUN npm run build

FROM nginx
COPY --from=build /app/build /usr/share/nginx/html